library(dplyr)
library(protr)
library(epitopes)

ncpus <- parallel::detectCores() - 1

hostIDs <- 9606 # Human 
# orgID <- 11103 # Hepacivirus C
# orgID <- 11102 # Hepacivirus
# orgID <- 11050 # Flaviviridae
# orgID <- 2732545 # Amarillovirales
# orgID <- 2732462 # Flasuviricetes
# orgID <- 2732406 # Kitrinoviricota
# orgID <- 2732396 # Orthornavirae
# orgID <- 2559587 #Riboviria
orgID <- 10239 #Viruses

savefile <- "./data/hep_c_data/viruses"

epitopes <- readRDS("./data/epitopes.rds") # Generated by get_IEDB() followed by get_LBCE()
proteins <- readRDS("./data/proteins.rds") # Generated by get_proteins()
taxonomy <- readRDS("./data/taxonomy.rds") # Generated by get_taxonomy()

peptides.list <- epitopes %>%
  filter_epitopes(orgIDs        = orgID,
                  orgID_column  = "sourceOrg_id",
                  hostID_column = "host_id",
                  tax_list      = taxonomy) %>%
  consolidate_data(proteins, only_exact = FALSE, ncpus = ncpus) %>%
  extract_peptides(min_peptide = 8, max_epitope = 25) %>%
  make_data_splits(proteins    = proteins,
                   target_props = c(.25, .75), # <--- desired split ratios
                   similarity_threshold = .99,
                   #return_front = 21,
                   ncpus = ncpus) %>%
  calc_features(local.features = c("Entropy","MolWeight", "AAtypes", "Atoms",   # <--- local features are calculated for the 15-AA windows and added to peptides.list$df
                                   "AAC", "CTDC", "CTDD", "CTDT", "BLOSUM"),
                global.features = c("AAC", "DC", "CTDC", "CTDD",                # <--- global features are calculated at the full protein level and added to peptides.list$proteins (needs a data join on df later, before training the models)
                                    "CTDT", "CTriad", "SOCN",
                                    "Entropy", "MolWeight", "AAtypes"),
                ncpus = ncpus) %>%
  save_peptide_list("./data/hep_c_data/viruses")

saveRDS(peptides.list, savefile)


#Decide train and test sets 
hep_c <- readRDS("./data/hep_c_data/hep_c/hep_c.rds")
hep_c<- hep_c$df
test_hep_c <- hep_c[hep_c$Info_split == "split_01_25", ] 
# get all Info_PedID's in test set
hep_c_test_id <- unique(test_hep_c$Info_PepID)
# Remove test proteins from all other data sets 
'%!in%' <- function(x,y)!('%in%'(x,y))
train_hep_c <- hep_c[hep_c$Info_PepID %!in% hep_c_test_id, ]
write.csv(train_hep_c, "hep_c_train.csv")
write.csv(test_hep_c, "hep_c_test.csv")

hepacivirus <- readRDS("./data/hep_c_data/hepacivirus/hepacivirus.rds")
hepacivirus <- hepacivirus$df
hepacivirus <- hepacivirus[hepacivirus$Info_PepID %!in% hep_c_test_id, ]
write.csv(hepacivirus, "hepacivirus.csv")

flaviviridae <- readRDS("./data/hep_c_data/flaviviridae/flaviviridae.rds")
flaviviridae <- flaviviridae$df
flaviviridae <- flaviviridae[flaviviridae$Info_PepID %!in% hep_c_test_id, ]
write.csv(flaviviridae, "flaviviridae.csv")

amarillovirales <- readRDS("./data/hep_c_data/amarillovirales/amarillovirales.rds")
amarillovirales <- amarillovirales$df
amarillovirales <- amarillovirales[amarillovirales$Info_PepID %!in% hep_c_test_id, ]
write.csv(amarillovirales, "amarillovirales.csv")

flasuviricetes <- readRDS("./data/hep_c_data/flasuviricetes/flasuviricetes.rds")
flasuviricetes <- flasuviricetes$df
flasuviricetes <- flasuviricetes[flasuviricetes$Info_PepID %!in% hep_c_test_id, ]
write.csv(flasuviricetes, "flasuviricetes.csv")

kitrinoviricota <- readRDS("./data/hep_c_data/kitrinoviricota/kitrinoviricota.rds")
kitrinoviricota <- kitrinoviricota$df
kitrinoviricota <- kitrinoviricota[kitrinoviricota$Info_PepID %!in% hep_c_test_id, ]
write.csv(kitrinoviricota, "kitrinoviricota.csv")

orthornavirae <- readRDS("./data/hep_c_data/orthornavirae/orthornavirae.rds")
orthornavirae <- orthornavirae$df
orthornavirae <- orthornavirae[orthornavirae$Info_PepID %!in% hep_c_test_id, ]
write.csv(orthornavirae, "orthornavirae.csv")


riboviria <- readRDS("./data/hep_c_data/riboviria/riboviria.rds")
riboviria <- riboviria$df
riboviria <- riboviria[riboviria$Info_PepID %!in% hep_c_test_id, ]
write.csv(riboviria, "riboviria.csv")

