library(dplyr)
library(protr)
library(epitopes)

ncpus <- parallel::detectCores() - 1

hostIDs <- NULL 
# hostIDs <- 9606 
# orgID <- 562 # Escherichia coli - Species 
# orgID <- 11103 # Hepacivirus C
# orgID <- 1485 # Clostridium 
# orgID <- 10376 # EBV
# orgID <- 5833 # Plasmodium falciparum - Species 
orgID <- 2104 # Mycoplasma pneumoniae - Species 

savefile <- "./feb_data/mycoplasma_pneumoniae_data.rds"

epitopes <- readRDS("./data/epitopes.rds") # Generated by get_IEDB() followed by get_LBCE()
proteins <- readRDS("./data/proteins.rds") # Generated by get_proteins()
taxonomy <- readRDS("./data/taxonomy.rds") # Generated by get_taxonomy()

t0 <- Sys.time()

peptides.list <- epitopes %>%
  filter_epitopes(orgIDs        = orgID,
                  orgID_column  = "sourceOrg_id",
                  hostID_column = "host_id",
                  tax_list      = taxonomy) %>%
  consolidate_data(proteins, only_exact = FALSE, ncpus = ncpus) %>%
  extract_peptides(min_peptide = 8, max_epitope = 25) %>%
  make_data_splits(proteins    = proteins,
                   target_props = c(.25, .75), # <--- desired split ratios
                   similarity_threshold = .5,
                   #return_front = 21,
                   ncpus = ncpus) %>%
  calc_features(local.features = c("AAC", "DC", "CTDC", "CTDT", "CTDD", "CTriad", "SOCN", "QSO", 
                                   "ScalesGap", "Entropy", "Atoms", "MolWeight", "AAtypes", "BLOSUM"),   # <--- local features are calculated for the 15-AA windows and added to peptides.list$df
                global.features = c("AAC", "DC", "TC", "CTDC", "CTDT", "CTDD", "CTriad", "SOCN", "QSO", 
                                    "ScalesGap", "Entropy", "Atoms", "MolWeight", "AAtypes", "BLOSUM"),  # <--- global features are calculated at the full protein level and added to peptides.list$proteins (needs a data join on df later, before training the models)
                ncpus = ncpus) %>%
  save_peptide_list("./feb_data/mycoplasma_pneumoniae")

saveRDS(peptides.list, savefile)

t1 <- Sys.time()
message("Elapsed time: ", signif(t1 - t0, 3), " ", units(t1 - t0))
